name: Testing era_test_node using e2e
on:
  workflow_call:

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: e2e
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: 'e2e-tests/yarn.lock'

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: era_test_node-${{ matrix.os }}.tar.gz
      
      - name: Start the era_test_node
        id: start_node
        run: |
          echo "Extracting era_test_node binary"
          tar -xzf era_test_node-${{ matrix.os }}.tar.gz
          chmod +x era_test_node
          echo "Starting node in background"
          ./era_test_node run 2>&1 | tee era_test_node_output.log &
          echo "PID=$!" >> $GITHUB_ENV

      - name: Launch tests
        id: launch
        run: |
          echo "Run tests"
          make test-e2e

      - name: Stop the era_test_node and print output logs
        id: stop_node
        if: always()
        run: |
          cat era_test_node_output.log
          kill $PID
